export function isChatModelSelectable(modelId?: string): boolean {
  if (!modelId) return false

  const normalized = modelId.toLowerCase()

  return ![
    /(?:^|[-_.])asr(?:[-_.]|$)/,
    /(?:^|[-_.])audio-transcription(?:[-_.]|$)/,
    /(?:^|[-_.])bigmodel-asr(?:[-_.]|$)/,
    /^dall-e(?:-|$)/,
    /(?:^|[-_.])doubao-asr(?:[-_.]|$)/,
    /(?:^|[-_.])doubao-seed-asr(?:[-_.]|$)/,
    /(?:^|[-_.])flux(?:[-_.]|$)/,
    /(?:^|[-_.])gen4(?:[-_.]|$)/,
    /^gpt-image(?:-|$)/,
    /(?:^|[-_.])hailuo(?:[-_.]|$)/,
    /(?:^|[-_.])hunyuan-video(?:[-_.]|$)/,
    /(?:^|[-_.])image(?:[-_.]|$)/,
    /(?:^|[-_.])ideogram(?:[-_.]|$)/,
    /(?:^|[-_.])imagen(?:[-_.]|$)/,
    /(?:^|[-_.])kling(?:[-_.]|$)/,
    /(?:^|[-_.])las-asr(?:[-_.]|$)/,
    /(?:^|[-_.])las_asr(?:[-_.]|$)/,
    /(?:^|[-_.])luma(?:[-_.]|$)/,
    /(?:^|[-_.])midjourney(?:[-_.]|$)/,
    /(?:^|[-_.])minimax-video(?:[-_.]|$)/,
    /(?:^|[-_.])nano-banana(?:[-_.]|$)/,
    /(?:^|[-_.])openspeech(?:[-_.]|$)/,
    /(?:^|[-_.])pika(?:[-_.]|$)/,
    /(?:^|[-_.])ray(?:[-_.]|$)/,
    /(?:^|[-_.])sd3(?:[-_.]|$)/,
    /(?:^|[-_.])sdxl(?:[-_.]|$)/,
    /(?:^|[-_.])video(?:[-_.]|$)/,
    /(?:^|[-_.])seedance(?:[-_.]|$)/,
    /(?:^|[-_.])seedane(?:[-_.]|$)/,
    /(?:^|[-_.])seedream(?:[-_.]|$)/,
    /(?:^|[-_.])sora(?:[-_.]|$)/,
    /(?:^|[-_.])speech-to-text(?:[-_.]|$)/,
    /(?:^|[-_.])stable-diffusion(?:[-_.]|$)/,
    /(?:^|[-_.])stable-image(?:[-_.]|$)/,
    /(?:^|[-_.])stt(?:[-_.]|$)/,
    /(?:^|[-_.])transcribe(?:[-_.]|$)/,
    /(?:^|[-_.])transcription(?:[-_.]|$)/,
    /(?:^|[-_.])veo(?:[-_.]|$)/,
    /(?:^|[-_.])volcengine-asr(?:[-_.]|$)/,
    /(?:^|[-_.])wan(?:[-_.]|$)/,
    /^whisper(?:-|$)/,
  ].some((pattern) => pattern.test(normalized))
}
